name: CI

on:
  pull_request:
  push:
    branches:
      - humble

defaults:
  run:
    shell: bash

jobs:
  build_container:
    name: Prepare and build ROS 2 Humble container for tests
    runs-on: ubuntu-22.04
    outputs:
      image: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and test Docker image
        uses: docker/build-push-action@v5  # https://github.com/docker/build-push-action
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ros2-ci:latest

  test_package:
    name: Test robot_collision_checking packages
    runs-on: ubuntu-22.04
    needs: build_container
    container:
      image: ${{ needs.prepare_container.outputs.image }}
    steps:
      - name: Run tests
        run: |
          source install/setup.bash
          colcon test --packages-select robot_collision_checking