name: CI

on:
  pull_request:
  push:
    branches:
      - humble

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and test Docker image
        uses: docker/build-push-action@v5  # https://github.com/docker/build-push-action
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ros2-ci:latest
          build-args: 
            - ROS_DISTRO=humble

      - name: Run tests
        uses: docker/run-action@v2
        with:
          image: ros2-ci:latest
          entrypoint: /bin/bash
          args: -c "source install/setup.bash && colcon test"